# Generated by Django 3.2.4 on 2021-06-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.IntegerField(default=1, verbose_name=((1, 'Cliente'), (2, 'Funcionario'))),
            preserve_default=False,
        ),
    ]
