# Generated by Django 3.2.4 on 2021-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(to='livros.Autor'),
        ),
    ]
