# Generated by Django 3.2.4 on 2021-06-24 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0006_livro_quem_alugou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quem_alugou',
        ),
        migrations.AddField(
            model_name='livro',
            name='quem_alugou',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
